language: node_js

matrix:
  include:
    - node_js: "4"
      env: COVERALLS=1
    - node_js: "6"

after_success:
  - if [ "$COVERALLS" = "1" ]; then npm run coveralls; fi

env:
  global:
    - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
